### ISSUE TITLE
Cannot load chartist.min.css

### ISSUE THREAD

**Issue by lost-valley** [eriklieben/aurelia-chartist#1]
Hi, I'm trying to use aurelia-chartist, but my app fails on load with:

```
Error: Failed loading required CSS file: 
http://localhost:9000/jspm_packages/npm/chartist@0.9.8/chartist.min.css
```

when the proper path should be:

```
http://localhost:9000/jspm_packages/npm/chartist@0.9.8/dist/chartist.min.css
```

If I modify the path in the @inlineView to include the dist folder, the app starts working.

Did you for example modify the package npm:chartist@0.9.8 and moved the files out of the `/dist` folder and into the `/` folder?

I don't see any special configuration in your `config.js` or `package.json` to tell SystemJS to look in the `/dist/` folder, so I'm kind of lost.

Thanks in advance :)

**Comment by eriklieben** [comment]
Thanks for the bug report!

You're right; I only used this package with a CLI installation and incorrectly specified paths in the config wich made it work in my case.

Added the 'dist' folder to the CSS require path and updated the installation instructions.

v1.0.2 should have the correct path/ should work again with jspm and cli.

**Comment by lost-valley** [comment]
Many thanks, I confim that it works :)
